import fs from 'fs';
import path from 'path';

const PROJECT_ROOT = process.cwd();
const ICONS_DIR = path.join(PROJECT_ROOT, 'src', 'assets', 'icons');
const OUTPUT_FILE = path.join(PROJECT_ROOT, 'src', 'components', 'icons.js');

function buildIcons() {
    console.log('🎨 Building SVG icon sprite...');
    
    if (!fs.existsSync(ICONS_DIR)) {
        console.warn(`⚠️ Warning: Icons directory not found at ${ICONS_DIR}`);
        return;
    }

    const files = fs.readdirSync(ICONS_DIR).filter(file => file.endsWith('.svg'));
    
    if (files.length === 0) {
        console.warn('⚠️ Warning: No SVG files found in icons directory.');
        return;
    }

    let symbolsHTML = '';

    for (const file of files) {
        const basename = path.basename(file, '.svg');
        const content = fs.readFileSync(path.join(ICONS_DIR, file), 'utf-8');
        
        // Extract viewBox
        const viewBoxMatch = content.match(/viewBox="([^"]+)"/i);
        const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24';

        // Extract inner SVG content (everything between <svg ...> and </svg>)
        let innerContent = '';
        const svgStartEnd = content.indexOf('>', content.indexOf('<svg'));
        const svgCloseStart = content.lastIndexOf('</svg>');
        
        if (svgStartEnd !== -1 && svgCloseStart !== -1) {
            innerContent = content.substring(svgStartEnd + 1, svgCloseStart).trim();
        } else {
            console.warn(`⚠️ Warning: Could not parse SVG content for ${file}`);
            continue;
        }

        symbolsHTML += `\n    <symbol id="icon-${basename}" viewBox="${viewBox}" fill="currentColor">\n        ${innerContent}\n    </symbol>`;
    }

    const outputContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/build-icons.js

const SVG_SPRITE = \`<svg xmlns="http://www.w3.org/2000/svg" style="display:none;" id="mblox-svg-sprite">${symbolsHTML}
</svg>\`;

export function injectSvgSprite() {
    if (typeof document !== 'undefined' && !document.getElementById('mblox-svg-sprite')) {
        document.body.insertAdjacentHTML('afterbegin', SVG_SPRITE);
    }
}
`;

    fs.writeFileSync(OUTPUT_FILE, outputContent, 'utf-8');
    console.log(`✅ Generated SVG sprite with ${files.length} icons at src/components/icons.js`);
}

buildIcons();
